---
- include_vars: ventumops-github.yml
#- include_vars: ventumapp-github.yml
- include_vars: docker.yml
 
- name: directory definition for keys 
  file:
    path: "{{ keys_dir }}"
    owner: root
    group: root
    mode: '0750'
    state: directory

- name: add keys for ventumops which is the machine user
  copy:
    content: "{{ ventumops }}"
    dest: "{{ keys_dir }}/ventumops-github.pem"
    decrypt: yes
    mode: '0600'

#- name: add keys for ventumapp which is the machine user
#  copy:
#    content: "{{ ventumapp }}"
#    dest: "{{ keys_dir }}/ventumapp-github.pem"
#    decrypt: yes
#    mode: '0600'

- name: add docker key to connect to docker hub repo
  copy:
    content: "{{ docker }}"
    dest: "{{ keys_dir }}/docker.key"
    decrypt: yes
    mode: '0600'

