---
- name: npm install
  become: yes
  command: npm install --unsafe-perm
  args:
    chdir: /opt/builds/Seed

- name: pm2 install
  become: yes
  command: npm install pm2 -g
  args:
    chdir: /opt/builds/Seed

- name: app run
  become: yes
  command: pm2 start --name Seed npm -- start
  args:
    chdir: /opt/builds/Seed
