---
# tasks file for docker
- name: install required software
  become: yes
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    update_cache: yes

- name: adds official Docker GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: adds official Docker repo
  shell: |
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: install Docker package
  become: yes
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python-docker
    update_cache: yes

# tasks file for docker-compose
- name: download the current stable release of Docker Compose
  shell: |
    sudo curl -L "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: apply executable permissions to the binary
  shell: |
    sudo chmod +x /usr/local/bin/docker-compose

- name: modify permissions to the executable
  shell: |
    sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
